### ISSUE TITLE
Need new repository?

### ISSUE THREAD

**Issue by manwar** [manwar/theweeklychallenge#127]
I am wondering do we need new repository where we can share our work with each other?

I want to keep the existing repository as clean as possible so that we can run it in parallel.

**Comment by jwnasambu** [comment]
@manwar Kindly is okay I work on this task please?

**Comment by manwar** [comment]
@jwnasambu sure
Do you have name of the new repository?
What folder structure are you suggesting?

**Comment by jwnasambu** [comment]
@manwar was thinking of `perlweeklychallenge-Outreachy` as the new repository name to track outreachy interns contribution. Concerning the folder structure am thinking of  `/outreachy-project
|-- backend
|   |-- src
|   |   |-- controllers
|   |   |-- models
|   |   |-- routes
|   |   |-- config
|   |   |-- app.js
|   |-- tests
|   |-- node_modules
|   |-- package.json
|-- frontend
|   |-- public
|   |-- src
|   |   |-- components
|   |   |-- pages
|   |   |-- styles
|   |   |-- App.js
|   |-- node_modules
|   |-- package.json
|-- docs
|-- .gitignore
|-- README.md
`

**Comment by manwar** [comment]
@jwnasambu good suggestion but I should make this clear that the project would be Perl based web interface using Dancer2.
Also the project is called "The Weekly Challenge". I suggest you create GitHub organisation with name, like "The-Weekly-Challenge".

If you are new to GitHub Organisation then I would suggest you read this:
https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations

**Comment by jwnasambu** [comment]
@manwar thanks so so much! you are right! am new to the community trying to onboard myself by getting involved in different tasks.

**Comment by jwnasambu** [comment]
@manwar Hello sir, this is what I have come with `https://github.com/jwnasambu/The-Weekly-Challenge` though finding away of changing the `owner` to be the organisation name. Kindly feel free to look at it please!

**Comment by manwar** [comment]
@jwnasambu please remove my name from the organisation, it doesn't look professional. Just keep it "TheWeeklyChallenge".

**Comment by jwnasambu** [comment]
@manwar Kindly review my changes https://github.com/TheWeeklyChallenge

**Comment by manwar** [comment]
@jwnasambu I am getting 404 page.

**Comment by jwnasambu** [comment]
@manwar sorry for the mistake done. Kindly this should work https://github.com/https-theweeklychallenge-org

**Comment by manwar** [comment]
@jwnasambu I have accepted the invite, thanks. Please make me admin.

**Comment by manwar** [comment]
@jwnasambu I noticed you created new github account "https-theweeklychallenge-org/people".
Can we please come up with some fancy organisation name instead?
Let me try this, "ChallengeForge" if you don't mind.

**Comment by jwnasambu** [comment]
@manwar Thanks for being patient with me . I have learnt something new. I have never created an organisation github  repository before. You are a good mentor. Am so happy you didn't abuse me.

**Comment by manwar** [comment]
@jwnasambu I have created this organisation and added you to the team:
https://github.com/ChallengeForge/TheWeeklyChallenge

**Comment by manwar** [comment]
@jwnasambu You are good person with attitude to learn and I respect that.

**Comment by manwar** [comment]
@jwnasambu do you mind if I delete this organisation?
https://github.com/https-theweeklychallenge-org

**Comment by manwar** [comment]
We have a repository now under a newly created GitHub organisation.

https://github.com/ChallengeForge

I would like to thank @jwnasambu for the helping hand.
It is safe to close the issue now.
