### ISSUE TITLE
Data migration script

### ISSUE THREAD

**Issue by manwar** [manwar/theweeklychallenge#130]
We would need script to migrate existing contributions to the new directory structure.

**Comment by joshuagaladima** [comment]
Hi, I suggested a contribution structure we can use here: https://github.com/manwar/theweeklychallenge/issues/128#issuecomment-1985610929

Is my suggestion okay? If so can I begin work on migrating the existing folder structure to the one I suggested?

**Comment by manwar** [comment]
@joshuagaladima I like your suggestion. Please start working in the new repository:
https://github.com/ChallengeForge/TheWeeklyChallenge

**Comment by manwar** [comment]
@joshuagaladima Please use Perl so that it can be maintained by others (me).

**Comment by joshuagaladima** [comment]
> @joshuagaladima I like your suggestion. Please start working in the new repository: https://github.com/ChallengeForge/TheWeeklyChallenge

Noted thank you Sir. I'll get to it.

**Comment by joshuagaladima** [comment]
> @joshuagaladima Please use Perl so that it can be maintained by others (me).

Definitely will.

**Comment by joshuagaladima** [comment]
Hello Sir, I have submitted a pull request for this task:

https://github.com/ChallengeForge/TheWeeklyChallenge/pull/2

**Comment by manwar** [comment]
@joshuagaladima I have reviewed your contribution and added some comments. Please take a look.
