### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by davorg** [manwar/theweeklychallenge#98]
In order for people to help fix problems with the site, it would be really useful to have a short README file that explains how to run Hugo to generate the site.

**Comment by voegelas** [comment]
I was able to generate the site with an old Hugo version from https://github.com/gohugoio/hugo/releases/tag/v0.67.0 by running `hugo` without arguments. There are still lots of changes in the generated documents but the site builds. I searched for my own changes with `git status content data static`.

**Comment by davorg** [comment]
Ah, that's a rather old version of Hugo (from March 2020). How did you work out that's the version that you need?

I just installed `hugo` from the Fedora repos and got [v0.93.3](https://github.com/gohugoio/hugo/releases/tag/v0.93.3) which doesn't work at all with this repo. Looks like the current version is [v0.114.1](https://github.com/gohugoio/hugo/releases/tag/v0.114.1).

@manwar, do you have any plans to fix the repo so it builds with a more recent version of `hugo`? Would you be interested in a pull request that fixes the problems? (I'm not saying I'll produce one, but I might have the time at some point.) Tell you what, I'll just raise an issue and you can do what you like with it.

**Comment by davorg** [comment]
Ah. I'll try a few more versions and see how up-to-date I can go.

I know nothing about Hugo either. But it might be fun to learn :-)

**Comment by baimamboukar** [comment]
Hello @davorg  👋
I'm Baimam, from Cameroon. My initial application for outreachy was accepted and I would like to work on this issue.

**Comment by baimamboukar** [comment]
> Hi @baimamboukar, that's good news. Congratulations on being accepted for Outreachy.
> 
> I'm not sure what the process is for deciding what you're going to work on, but I think that this (and the [other outstanding issue on this project](https://github.com/manwar/theweeklychallenge/issues/110)) would be great places to start.
> 
> Let me know if I can be any help.

Hey @davorg ! Thank You ✨

I already started working on this issue, I will soon raise the PR.

**Comment by manwar** [comment]
@baimamboukar As part of Outreachy Program, we are planning to get rid off Hugo altogether. I would suggest, please don't spend your energy and time on this.
Instead, you can help us creating template for new web interface. 
You can discuss this and other topics on the Slack channel "the-weekly-challenge".

**Comment by baimamboukar** [comment]
Hello @manwar 👋

Thanks very much for the information!
